### ISSUE TITLE
DRP failed to installed

### ISSUE THREAD

**Issue by kslong** [sdss/lvmdrp#1]
The DRP failed to install for me in a conda environment I set up for it on my ubuntu linux box.  It failed on the pip install step, with the following error

````
Requirement already satisfied: sniffio>=1.1 in /home/long/anaconda3/envs/lvm_drp/lib/python3.7/site-packages (from anyio<4,>=3.1.0->jupyter-server>=1.8->nbclassic>=0.4.7->notebook->jupyter->drp==0.1.0.dev0) (1.2.0)
Requirement already satisfied: pycparser in /home/long/anaconda3/envs/lvm_drp/lib/python3.7/site-packages (from cffi>=1.0.1->argon2-cffi-bindings->argon2-cffi->notebook->jupyter->drp==0.1.0.dev0) (2.21)
Building wheels for collected packages: drp
  Building wheel for drp (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      error in drp setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Parse error at "'-r requi'": Expected W:(0-9A-Za-z)
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for drp
  Running setup.py clean for drp
Failed to build drp
Installing collected packages: drp
  Attempting uninstall: drp
    Found existing installation: drp 0.1.0.dev0
    Uninstalling drp-0.1.0.dev0:
      Successfully uninstalled drp-0.1.0.dev0
  Running setup.py install for drp ... done
  DEPRECATION: drp was installed using the legacy 'setup.py install' method, because a wheel could not be built for it. pip 23.1 will enforce this behaviour change. A possible replacement is to fix the wheel build issue reported above. Discussion can be found at https://github.com/pypa/pip/issues/8368
Successfully installed drp-0.1.0.dev0
(lvm_drp) ~/SDSS/lvmdrp: drp sky configureSkyModel
Traceback (most recent call last):
  File "/home/long/anaconda3/envs/lvm_drp/bin/drp", line 20, in <module>
    from drp.main import math
ModuleNotFoundError: No module named 'drp'
````

The commit I tried to install was 

139f7679ef24bb949b5d49c63a7d51c59ab45e2b

**Comment by ajmejia** [comment]
Hi Knox, this is an old commit. Did you "git checkout -b development"? I updated the README to add this extra step while we're testing the code.

**Comment by kslong** [comment]
Yes, here are the exact commands:

````
  524  git clone --recurse-submodules -j8 git@github.com:sdss/lvmdrp.git
  525  ls
  526  cd lvmdrp
  527  git checkout -b development
  528  pip install .
  529  drp sky configureSkyModel
````

**Comment by ajmejia** [comment]
This are the commands that you need to do after switching to the development branch:

git branch --set-upstream-to=origin/development development
git pull

Please let me know if this works.

**Comment by kslong** [comment]
I have now done this, and I got further:

````
 513  git branch --set-upstream-to=origin/development development
  514  git pull
  516  pip install .
````
but I now get an error on the ESO Sky model phase

````
     
      Step 1: Choose root installation directory <INST_DIR>: /home/long/anaconda3/envs/lvm_drp/lib/skycorr
      
      Is this OK [Y/n]? y
      
      WARNING:  Using '/home/long/anaconda3/envs/lvm_drp/lib/skycorr'
                probably exceeds the 80 character limit of path+filenames
                introduced by the Fortran codes LBLRTM.
                May cause problems using the radiative transfer codes!
                Proceed with this installation directory (y/N)? y
      
      
      Oops, it seems that the installation already exists....
      Proceed (will overwrite existing files without further warning) (y/N):successfully installed skycorr
      successfully tested skycorr
      preparing to install skymodel
      successfully extracted sky model installer
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/long/SDSS/lvmdrp/setup.py", line 399, in <module>
          run(packages, install_requires)
        File "/home/long/SDSS/lvmdrp/setup.py", line 350, in run
          "install": InsCommand
        File "/home/long/anaconda3/envs/lvm_drp/lib/python3.7/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/home/long/anaconda3/envs/lvm_drp/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/home/long/anaconda3/envs/lvm_drp/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/home/long/anaconda3/envs/lvm_drp/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/home/long/anaconda3/envs/lvm_drp/lib/python3.7/site-packages/setuptools/dist.py", line 1208, in run_command
          super().run_command(command)
        File "/home/long/anaconda3/envs/lvm_drp/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/long/SDSS/lvmdrp/setup.py", line 313, in run
          install_eso_routines()
        File "/home/long/SDSS/lvmdrp/setup.py", line 171, in install_eso_routines
          shutil.copytree("config", os.path.join(SKYMODEL_INST_PATH, "sm-01_mod1", "config"), dirs_exist_ok=True)
      TypeError: copytree() got an unexpected keyword argument 'dirs_exist_ok'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> lvmdrp

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
````

**Comment by kslong** [comment]
I have set up a conda environment with python 3.8, actually 3.8.16.

I started from scratch and cloned the drp repository again.

This time I used, 

conda checkout development  (without the -b which left you on the main branch)

When I tried pip install .  I get the following:

````
pip install .
Processing /home/long/SDSS/lvmdrp
  Preparing metadata (setup.py) ... done
Collecting lvmsurveysim@ git+https://github.com/sdss/lvmsurveysim.git@0.8.3
  Cloning https://github.com/sdss/lvmsurveysim.git (to revision 0.8.3) to /tmp/pip-install-6s73h2rd/lvmsurveysim_7f5b3a78c2fc4a51bc29ef23641f9c68
  Running command git clone --filter=blob:none --quiet https://github.com/sdss/lvmsurveysim.git /tmp/pip-install-6s73h2rd/lvmsurveysim_7f5b3a78c2fc4a51bc29ef23641f9c68
  Running command git checkout -q 0884e783c1fb8b71e6cee5cdd8a0bcdcba00440a
  Resolved https://github.com/sdss/lvmsurveysim.git to commit 0884e783c1fb8b71e6cee5cdd8a0bcdcba00440a
  Preparing metadata (setup.py) ... done
Collecting sdss-datamodel@ git+https://github.com/sdss/datamodel.git@0.5.2
  Cloning https://github.com/sdss/datamodel.git (to revision 0.5.2) to /tmp/pip-install-6s73h2rd/sdss-datamodel_14791b6049a24ba0bd7de4316da7e6aa
  Running command git clone --filter=blob:none --quiet https://github.com/sdss/datamodel.git /tmp/pip-install-6s73h2rd/sdss-datamodel_14791b6049a24ba0bd7de4316da7e6aa
Username for 'https://github.com': kslong
Password for 'https://kslong@github.com': 
  remote: Support for password authentication was removed on August 13, 2021.
  remote: Please see https://docs.github.com/en/get-started/getting-started-with-git/about-remote-repositories#cloning-with-https-urls for information on currently recommended modes of authentication.
  fatal: Authentication failed for 'https://github.com/sdss/datamodel.git/'
  error: subprocess-exited-with-error
  
  × git clone --filter=blob:none --quiet https://github.com/sdss/datamodel.git /tmp/pip-install-6s73h2rd/sdss-datamodel_14791b6049a24ba0bd7de4316da7e6aa did not run successfully.
  │ exit code: 128
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× git clone --filter=blob:none --quiet https://github.com/sdss/datamodel.git /tmp/pip-install-6s73h2rd/sdss-datamodel_14791b6049a24ba0bd7de4316da7e6aa did not run successfully.
│ exit code: 128
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
````

This does look like a problem to me.  I would have expected the command to be more like this one, for one of my own repositiories

git@github.com:agnwinds/python.git

**Comment by joelbrownstein** [comment]
Hi @kslong I invited you to the SDSS GitHub Organization:

`You've invited Knox S. Long to SDSS! They'll be receiving an email shortly. They can also visit https://github.com/sdss to accept the invitation. `

Once you accept the invitation, the error regarding access to https://github.com/sdss/datamodel.git should not occur.

Thanks,
Joel

**Comment by ajmejia** [comment]
This doesn't seem to be an issue anymore. The installation process has been largely simplified since then.
