### ISSUE TITLE
Failures and negative fluxes for several exposures with calibrations after MJD=60388

### ISSUE THREAD

**Issue by oegorov** [sdss/lvmdrp#127]
I tried to reduce 35 exposures for NGC3199 and its surroundings with drp 1.0.4dev (last update ~25/07). Calibrations and lvmcore were updated on the same date. 
In this set, I have ~26 early science +1 survey exposures taken no later than 60368, and 8 tiles from the survey taken after mjd=60388. 
All 27 earlier exposures were reduced perfectly, and all 8 latest survey tiles failed. 
Among them, 3 frames were not reduced (drp crashed), and 5 others resulted in negative sensitive curves. 
These exposure numbers are 15010, 16869, 17975 (can't reduce) and 15074, 16812, 16870, 16872, 17389 (negative fluxes)
Could it be due to some problems with particular calibration files for these MJDs (60388 and 60402)? 

As an example, here is an error I got for 15010. Note - it was reduced with 1.0.3 (on SAS), but the fluxes are negative. Therefore, these two issues may be related to each other.

> [INFO]: Mean stdstar sensitivity in b : -9.838270748989868e-13
> [INFO]: appending FLUXCAL_STD table
> [INFO]: Using Gaia CACHE DIR '/data/LVM/sdsswork/lvm/sandbox/calib/gaia_cache'
> [INFO]: loading input RSS file 'lvm-hobject-b-00015010.fits'
> querying for ids ...
> [INFO]: science fiberid '1744', star '5258713740538536320', secz '1.20'
> [ERROR]: Failed to reduce science frame mjd 60395 exposure 15010: cannot reshape array of size 0 into shape (0,newaxis)
> Traceback (most recent call last):
>   File "/home/egorov/PyWorkspace/Laptop/LVM/lvmdrp/python/lvmdrp/main.py", line 1835, in run_drp
>     science_reduction(expnum, use_fiducial_master=True,
>   File "/home/egorov/PyWorkspace/Laptop/LVM/lvmdrp/python/lvmdrp/main.py", line 1666, in science_reduction
>     fluxcal_sci_ifu_stars(hsci_path, GAIA_CACHE_DIR=MASTERS_DIR+'/gaia_cache')
>   File "/home/egorov/PyWorkspace/Laptop/LVM/lvmdrp/python/lvmdrp/functions/fluxCalMethod.py", line 537, in fluxcal_sci_ifu_stars
>     rss, res_sci = science_sensitivity(rss, res_sci, ext, GAIA_CACHE_DIR, NSCI_MAX=NSCI_MAX, plot=plot)
>   File "/home/egorov/PyWorkspace/Laptop/LVM/lvmdrp/python/lvmdrp/functions/fluxCalMethod.py", line 375, in science_sensitivity
>     obsflux = fluxcal.interpolate_mask(obswave, obsflux, ~np.isfinite(obsflux))
>   File "/home/egorov/PyWorkspace/Laptop/LVM/lvmdrp/python/lvmdrp/core/fluxcal.py", line 334, in interpolate_mask
>     f = interpolate.interp1d(known_x, known_v, kind=kind, fill_value=fill_value, bounds_error=False)
>   File "/home/egorov/anaconda3/envs/lvmdrp/lib/python3.10/site-packages/scipy/interpolate/_interpolate.py", line 532, in __init__
>     self._y = self._reshape_yi(self.y)
>   File "/home/egorov/anaconda3/envs/lvmdrp/lib/python3.10/site-packages/scipy/interpolate/_polyint.py", line 112, in _reshape_yi
>     return yi.reshape((yi.shape[0], -1))
> ValueError: cannot reshape array of size 0 into shape (0,newaxis)

**Comment by ndrory** [comment]
Oleg, Jose,

On Aug 1, 2024, at 7:57 AM, Oleg Egorov ***@***.***> wrote:

[INFO]: Mean stdstar sensitivity in b : -9.838270748989868e-13

Are these files from the period where we did not correctly expose the standard stars? It seems that it is trying to calculate the sensitivity curve from standard stars, but we get a negative value. We currently do not fall back on the field star calibration in such a case.

N.


-- Niv Drory --
McDonald Observatory / Dept. of Astronomy
The University of Texas at Austin
Tel: +1 512 471 6197
http://www.as.utexas.edu/~drory

**Comment by oegorov** [comment]
Hmm... I don't remember when it was, but it could be. The good news is that using sensitivity derived from the field stars for the exposures with negative fluxes, I get results consistent with other (good) exposures.
