### ISSUE TITLE
Reduce2D from lvmdrp 1.1.1dev fails for at least some early science exposures

### ISSUE THREAD

**Issue by oegorov** [sdss/lvmdrp#162]
I am trying to reduce the early science exposures (tileid=11111) with the new version of drp. There is an error with the extraction of astrometry. Perhaps some header fix is required? 
I think the same error was present in 1.0.3, as the data for these exposures are missing on SAS.
(perhaps incomplete) list of the affected exposures: 
mjd=60185, ids = 3962, 3963, 3964, 3965, 3966, 3967, 3968, 3969
mjd=60179, ids = 3602, 3603, 3604, 3605, 3606
mjd=60208, id = 5351

```
[ERROR]: Failed to reduce science frame mjd 60185 exposure 3962: 'list' object has no attribute 'ra'
Traceback (most recent call last):
  File "/home/egorov/PyWorkspace/Laptop/LVM/lvmdrp/python/lvmdrp/main.py", line 1789, in run_drp
    science_reduction(expnum, use_longterm_cals=True,
  File "/home/egorov/PyWorkspace/Laptop/LVM/lvmdrp/python/lvmdrp/main.py", line 1525, in science_reduction
    reduce_2d(mjd=sci_mjd, calibrations=calibs, expnums=[sci_expnum], reject_cr=reject_cr, skip_done=False)
  File "/home/egorov/PyWorkspace/Laptop/LVM/lvmdrp/python/lvmdrp/main.py", line 1448, in reduce_2d
    add_astrometry(in_image=dframe_path, out_image=dframe_path, in_agcsci_image=agcsci_path, in_agcskye_image=agcskye_path, in_agcskyw_image=agcskyw_path)
  File "/home/egorov/PyWorkspace/Laptop/LVM/lvmdrp/python/lvmdrp/functions/imageMethod.py", line 3615, in add_astrometry
    RAobs_sci, DECobs_sci, PAobs_sci = getobsparam('sci')
  File "/home/egorov/PyWorkspace/Laptop/LVM/lvmdrp/python/lvmdrp/functions/imageMethod.py", line 3571, in getobsparam
    RAobs=IFUcencoords.ra.value
AttributeError: 'list' object has no attribute 'ra'
```

**Comment by ndrory** [comment]
Oleg, even if you manage to reduce the data, the calibrations for this epoch are still not final, so your results will not meet your expectations.

**Comment by ndrory** [comment]
Fixed in https://github.com/sdss/lvmdrp/commit/7a01361322311559ca35452d654730c0acd013a4
