### ISSUE TITLE
Failure during measurement of fiber shifts

### ISSUE THREAD

**Issue by ndrory** [sdss/lvmdrp#165]
ERROR on tileid, mjd, exposure: 1028288, 60495, 20699
Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/sdss50/software/git/sdss/lvmdrp/1.1.0/python/lvmdrp/main.py", line 1789, in run_drp
    science_reduction(expnum, use_longterm_cals=True,
  File "/uufs/chpc.utah.edu/common/home/sdss50/software/git/sdss/lvmdrp/1.1.0/python/lvmdrp/main.py", line 1553, in science_reduction
    extract_spectra(in_image=lsci_path, out_rss=xsci_path, in_trace=mtrace_path, in_fwhm=mwidth_path,
  File "/uufs/chpc.utah.edu/common/home/sdss50/software/git/sdss/lvmdrp/1.1.0/python/lvmdrp/utils/decorators.py", line 60, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/uufs/chpc.utah.edu/common/home/sdss50/software/git/sdss/lvmdrp/1.1.0/python/lvmdrp/functions/imageMethod.py", line 2626, in extract_spectra
    trace_mask, shifts, median_shift, std_shift, _ = _fix_fiber_thermal_shifts(img, trace_mask, 2.5,
                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/uufs/chpc.utah.edu/common/home/sdss50/software/git/sdss/lvmdrp/1.1.0/python/lvmdrp/functions/imageMethod.py", line 389, in _fix_fiber_thermal_shifts
    column_shifts = image.measure_fiber_shifts(fiber_model, trace_cent, columns=columns, column_width=column_width, shift_range=shift_range, axs=axs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/uufs/chpc.utah.edu/common/home/sdss50/software/git/sdss/lvmdrp/1.1.0/python/lvmdrp/core/image.py", line 767, in measure_fiber_shifts
    _, shifts[j], _ = _cross_match_float(s1, s2, numpy.array([1.0]), shift_range, gauss_window=[-3,3], min_peak_dist=5.0, ax=axs_cc[j])
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/uufs/chpc.utah.edu/common/home/sdss50/software/git/sdss/lvmdrp/1.1.0/python/lvmdrp/core/spectrum1d.py", line 325, in _cross_match_float
    cross_corr /= norm(stretched_signal1) * norm(obs_spec_)
                                            ^^^^^^^^^^^^^^^
  File "/uufs/chpc.utah.edu/common/home/sdss50/software/pkg/miniconda/3.11_lvmdrp/lib/python3.11/site-packages/scipy/linalg/_misc.py", line 146, in norm
    a = np.asarray_chkfinite(a)
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/uufs/chpc.utah.edu/common/home/sdss50/software/pkg/miniconda/3.11_lvmdrp/lib/python3.11/site-packages/numpy/lib/function_base.py", line 630, in asarray_chkfinite
    raise ValueError(
ValueError: array must not contain infs or NaNs

**Comment by ajmejia** [comment]
20699 was marked as BAD by the QC pipeline. After merging of PR #170 we are correctly skipping bad exposures.
The same issue happens in a number of exposures, some of them taken during engineering nights, which we are correctly skipping as well (see ebadfde8d861c311afcd9f580410efef30663408).

However we need to run the pipeline on exposures presenting this same issue before we close this.

**Comment by ajmejia** [comment]
Confirmed that all instances of this error are exposures either taken during engineering nights or marked as BAD by the QC pipeline.
