### ISSUE TITLE
Do not put NaN values in FITS headers in v1.1

### ISSUE THREAD

**Issue by ndrory** [sdss/lvmdrp#167]
ERROR on tileid, mjd, exposure: 11111, 60459, 18396
Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/sdss50/software/git/sdss/lvmdrp/1.1.0/python/lvmdrp/main.py", line 1789, in run_drp
    science_reduction(expnum, use_longterm_cals=True,
  File "/uufs/chpc.utah.edu/common/home/sdss50/software/git/sdss/lvmdrp/1.1.0/python/lvmdrp/main.py", line 1616, in science_reduction
    fluxcal_sci_ifu_stars(hsci_path, GAIA_CACHE_DIR=MASTERS_DIR+'/gaia_cache')
  File "/uufs/chpc.utah.edu/common/home/sdss50/software/git/sdss/lvmdrp/1.1.0/python/lvmdrp/functions/fluxCalMethod.py", line 574, in fluxcal_sci_ifu_stars
    rss.setHdrValue(f"SCISENM{label}", np.nanmean(mean_sci[1000:3000]), f"Mean scistar sensitivity in {channel}")
  File "/uufs/chpc.utah.edu/common/home/sdss50/software/git/sdss/lvmdrp/1.1.0/python/lvmdrp/core/header.py", line 155, in setHdrValue
    self._header[keyword] = (value, comment)
    ~~~~~~~~~~~~^^^^^^^^^
  File "/uufs/chpc.utah.edu/common/home/sdss50/software/pkg/miniconda/3.11_lvmdrp/lib/python3.11/site-packages/astropy/io/fits/header.py", line 222, in __setitem__
    self._update((key, value, comment))
  File "/uufs/chpc.utah.edu/common/home/sdss50/software/pkg/miniconda/3.11_lvmdrp/lib/python3.11/site-packages/astropy/io/fits/header.py", line 1678, in _update
    self.append(card)
  File "/uufs/chpc.utah.edu/common/home/sdss50/software/pkg/miniconda/3.11_lvmdrp/lib/python3.11/site-packages/astropy/io/fits/header.py", line 1144, in append
    card = Card(*card)
           ^^^^^^^^^^^
  File "/uufs/chpc.utah.edu/common/home/sdss50/software/pkg/miniconda/3.11_lvmdrp/lib/python3.11/site-packages/astropy/io/fits/card.py", line 201, in __init__
    self.value = value
    ^^^^^^^^^^
  File "/uufs/chpc.utah.edu/common/home/sdss50/software/pkg/miniconda/3.11_lvmdrp/lib/python3.11/site-packages/astropy/io/fits/card.py", line 348, in value
    raise ValueError(
ValueError: Floating point nan values are not allowed in FITS headers.

**Comment by ajmejia** [comment]
This exposure is within the range of MJDs that we're skipping here: https://github.com/sdss/lvmcore/blob/master/etc/exclude_mjds.txt.
