### ISSUE TITLE
Astrometry failure in early science data

### ISSUE THREAD

**Issue by ajmejia** [sdss/lvmdrp#188]
Some early science data may have no astrometry information in the header, producing the following error:

`ERROR on tileid, mjd, exposure: 11111, 60181, 3683
Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u6050347/lvmdrp/python/lvmdrp/main.py", line 1845, in run_drp
    science_reduction(expnum, use_longterm_cals=True,
  File "/uufs/chpc.utah.edu/common/home/u6050347/lvmdrp/python/lvmdrp/main.py", line 1549, in science_reduction
    reduce_2d(mjd=sci_mjd, calibrations=calibs, expnums=[sci_expnum], reject_cr=reject_cr, skip_done=False)
  File "/uufs/chpc.utah.edu/common/home/u6050347/lvmdrp/python/lvmdrp/main.py", line 1458, in reduce_2d
    add_astrometry(in_image=dframe_path, out_image=dframe_path, in_agcsci_image=agcsci_path, in_agcskye_image=agcskye_path, in_agcskyw_image=agcskyw_path)
  File "/uufs/chpc.utah.edu/common/home/u6050347/lvmdrp/python/lvmdrp/functions/imageMethod.py", line 3620, in add_astrometry
    getfibradec('sci', platescale=FIDUCIAL_PLATESCALE)
  File "/uufs/chpc.utah.edu/common/home/u6050347/lvmdrp/python/lvmdrp/functions/imageMethod.py", line 3615, in getfibradec
    fibcoords=w.pixel_to_world(xfib,yfib).to_table()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/uufs/chpc.utah.edu/common/home/sdss50/software/pkg/miniconda/3.11_lvmdrp/lib/python3.11/site-packages/astropy/wcs/wcsapi/high_level_api.py", line 327, in pixel_to_world
    world_values = self.low_level_wcs.pixel_to_world_values(*pixel_arrays)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/uufs/chpc.utah.edu/common/home/sdss50/software/pkg/miniconda/3.11_lvmdrp/lib/python3.11/site-packages/astropy/wcs/wcsapi/fitswcs.py", line 336, in pixel_to_world_values
    world = self.all_pix2world(*pixel_arrays, 0)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/uufs/chpc.utah.edu/common/home/sdss50/software/pkg/miniconda/3.11_lvmdrp/lib/python3.11/site-packages/astropy/wcs/wcs.py", line 1558, in all_pix2world
    return self._array_converter(self._all_pix2world, "output", *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/uufs/chpc.utah.edu/common/home/sdss50/software/pkg/miniconda/3.11_lvmdrp/lib/python3.11/site-packages/astropy/wcs/wcs.py", line 1548, in _array_converter
    return _return_list_of_arrays(axes, origin)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/uufs/chpc.utah.edu/common/home/sdss50/software/pkg/miniconda/3.11_lvmdrp/lib/python3.11/site-packages/astropy/wcs/wcs.py", line 1498, in _return_list_of_arrays
    output = func(xy, origin)
             ^^^^^^^^^^^^^^^^
astropy.wcs._wcs.InvalidTransformError: ERROR 7 in wcsset() at line 2693 of file cextern/wcslib/C/wcs.c:
Ill-conditioned coordinate transformation parameter.`

**Comment by ajmejia** [comment]
Fixed in 5e2adeb26da8f6657add082945a6831f99044e8b
