### ISSUE TITLE
drp sky installESOSky fails on MAC

### ISSUE THREAD

**Issue by kslong** [sdss/lvmdrp#5]
While I can install the ESOSky model on my linux machine, this step fails on my MAC (Monterey).  The procedure starts properly, but regardless of the options I try, it always simply stalls.  After waiting some period of time, a keyboard interrupt shows it is failing on this step:

````
^C[ERROR]: Traceback (most recent call last):
  File "/Users/long/anaconda3/envs/lvmdrp/bin/drp", line 159, in <module>
    eval(run_task)
  File "<string>", line 1, in <module>
  File "/Users/long/anaconda3/envs/lvmdrp/lib/python3.8/site-packages/lvmdrp/functions/skyMethod.py", line 151, in installESOSky_drp
    skycorr_installer.wait()
  File "/Users/long/anaconda3/envs/lvmdrp/lib/python3.8/site-packages/pexpect/pty_spawn.py", line 688, in wait
    exitstatus = ptyproc.wait()
  File "/Users/long/anaconda3/envs/lvmdrp/lib/python3.8/site-packages/ptyprocess/ptyprocess.py", line 670, in wait
    pid, status = os.waitpid(self.pid, 0)
````

**Comment by ajmejia** [comment]
`installESOSky_drp` was deprecated and removed in PR #21.
