### ISSUE TITLE
Some older datasets without POSKYEPA keyword are failing

### ISSUE THREAD

**Issue by tonywong94** [sdss/lvmdrp#83]
When processing some early science data through the DRP last weekend (using commit e438680, 26 April) all data sets before MJD 60187 were failing.  For example, MJD 60180, exposure 3679.  Here is some example output:

```
**************************************
**** ADDING ASTROMETRY TO SLITMAP ****
**************************************
WARNING: FITSFixedWarning: The WCS transformation has more axes (2) than the image it is associated with (0) [astropy.wcs.wcs]
[ERROR]: Traceback (most recent call last):
  File "/Users/tonywong/miniconda3/envs/lvmdrp/bin/drp", line 276, in <module>
    cli()
  File "/Users/tonywong/miniconda3/envs/lvmdrp/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/Users/tonywong/miniconda3/envs/lvmdrp/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/Users/tonywong/miniconda3/envs/lvmdrp/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/tonywong/miniconda3/envs/lvmdrp/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/tonywong/miniconda3/envs/lvmdrp/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/tonywong/miniconda3/envs/lvmdrp/bin/drp", line 174, in quick_reduction
    quick_science_reduction(expnum, use_fiducial_master, skip_sky_subtraction,
  File "/Users/tonywong/miniconda3/envs/lvmdrp/lib/python3.9/site-packages/lvmdrp/functions/run_quickdrp.py", line 189, in quick_science_reduction
    image_tasks.add_astrometry(in_image=dsci_path, out_image=dsci_path, in_agcsci_image=agcsci_path, in_agcskye_image=agcskye_path, in_agcskyw_image=agcskyw_path)
  File "/Users/tonywong/miniconda3/envs/lvmdrp/lib/python3.9/site-packages/lvmdrp/functions/imageMethod.py", line 4074, in add_astrometry
    RAobs_skye, DECobs_skye, PAobs_skye = getobsparam('skye')
  File "/Users/tonywong/miniconda3/envs/lvmdrp/lib/python3.9/site-packages/lvmdrp/functions/imageMethod.py", line 4065, in getobsparam
    PAobs=org_img._header[f'PO{tel}PA'.capitalize()]
  File "/Users/tonywong/miniconda3/envs/lvmdrp/lib/python3.9/site-packages/astropy/io/fits/header.py", line 170, in __getitem__
    card = self._cards[self._cardindex(key)]
  File "/Users/tonywong/miniconda3/envs/lvmdrp/lib/python3.9/site-packages/astropy/io/fits/header.py", line 1726, in _cardindex
    raise KeyError(f"Keyword {keyword!r} not found.")
KeyError: "Keyword 'POSKYEPA' not found."
```
Typically this keyword has value 0.0, so maybe a simple fix would be to assume it's 0 if it's not in the FITS file?  Note that there is also a `POSKYWPA` keyword that probably has the same issue.  If this has already been fixed in a more recent update, please ignore.

**Comment by ajmejia** [comment]
This was fixed on PR #100.
